config/routes.rb
Rails.application.routes.draw do
  require 'csv'
  get 'students/index'
  root 'students#index'

  resources :students
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
  def self.to_csv
    attributes = %w{id email name}

    CSV.generate(headers: true) do |csv|
      csv << attributes

      all.find_each do |user|
        csv << attributes.map{ |attr| user.send(attr) }
      end
    end
  end
end

app/models/student.rb
class Student < ApplicationRecord
	require 'csv'
	
	def self.to_csv
    attributes = %w{id name email password address}

    CSV.generate(headers: true) do |csv|
      csv << attributes

      all.find_each do |user|
        csv << attributes.map{ |attr| user.send(attr) }
      end
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  require 'csv'
  before_action :find_student, only:[:show, :edit, :update, :destroy]

  def index
    @student = Student.all
    @student = @student.paginate(page: params[:page], per_page: 7)
    respond_to do |format|
      # binding.pry
      format.html # index.html.erb
      # @student = Student.order(:name).page params[:page]
      format.csv { send_data Student.to_csv, filename: "student #{Date.today}.csv" }
    end
  end

 def new
    @student = Student.new
  end

  def create
    @student = Student.new(student_params)
    if @student.save
      redirect_to students_path
    else
      render :new
    end
  end

  def show
    # @student = Student.find_by(id: params[:id])
  end

  def edit
    # @student = Student.find_by(id: params[:id])
  end

  def update
    # @student = Student.find_by(id: params[:id])
    if @student.update(student_params)
     redirect_to root_path
    else
     render :edit
    end
  end

  def destroy
    # @student = Student.find_by(id: params[:id])
    if @student.destroy
      redirect_to root_path
    end
  end

  private

  def student_params
    params.require(:student).permit(:name, :email, :password, :address)
  end

  def find_student
    @student = Student.find_by(id: params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SidekiqDemo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/students/edit.html.erb
<h3 style = "text-align: center;">Update Form</h3>
<div class="container-fluid">
	<div class="row">
		<div class="col-sm-4"></div>
		<div class="col-sm-4">
			<%= form_with model: @student do |form|%>
				<%= form.label :name %><br>
				<%= form.text_field :name, class: "form-control"%>
				<%= form.label :email %>
				<%= form.text_field :email, class: "form-control" %>
				<%= form.label :password%>
				<%= form.text_field :password, class: "form-control"%>
				<%= form.label :address%>
				<%= form.text_field :address, class: "form-control"%><br>
				<%= form.submit "Update"%>
			<% end %>			
		</div>
		<div class="col-sm-4"></div>
	</div>
</div>

app/views/students/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12">
      <marquee behavior = "alternate"; scrollamount = " 30 px;">
        <h1>Chetu Private Limited</marquee>
        <hr>

      <table class="table">
          <thead>
            <tr>
              <th scope="col">Name</th>
              <th scope="col">Email</th>
              <th scope="col">Password</th>
              <th scope="col">Address</th>
              <th scope="col"><%= link_to "Add student", new_student_path , class: "btn btn-primary"%>
              <%=link_to "Export CSV", students_path(format: 'csv'), class: "btn btn-warning"%>
              </th>
            </tr>
          </thead>
          <tbody>
        <% @student.each do |student|%>
          <tr>
            <td><%= student.name%></td>
            <td><%= student.email %></td>
            <td><%= student.password %></td>
            <td><%= student.address %></td>
            <td><%= link_to "show", student_path(student) , class: "btn btn-primary" %>
            <%= link_to "Edit", edit_student_path(student) , class: "btn btn-primary" %>
            <%= link_to "Delete", student_path(student) , class: "btn btn-danger", data: {turbo_method: :delete, turbo_confirm: "Are You Sure"}%><td>
          </tr>
        <% end %>
          </tbody>
      </table>
      <div class="digg_pagination">
        <div class="page_info">
          <%= page_entries_info @student %>
        </div>
        <%= will_paginate @student, :container => false %>
      </div>
    </div>
  </div>
</div>

app/views/students/new.html.erb
<h3 style = "text-align: center;">Student Form</h3>
<div class="container-fluid">
	<div class="row">
		<div class="col-sm-4"></div>
		<div class="col-sm-4">
			<%= form_with model: @student do |form|%>
				<%= form.label :name %><br>
				<%= form.text_field :name, class: "form-control"%>
				<%= form.label :email %>
				<%= form.text_field :email, class: "form-control" %>
				<%= form.label :password%>
				<%= form.text_field :password, class: "form-control"%>
				<%= form.label :address%>
				<%= form.text_field :address, class: "form-control"%><br>
				<%= form.submit "submit"%>
			<% end %>			
		</div>
		<div class="col-sm-4"></div>
	</div>
</div>

app/views/students/show.html.erb
<div class="container-fluid">
<h3 style = "text-align: center;">Update Form</h3>
	<div class="row">
		<div class="col-sm-4"></div>
		<div class="col-sm-4">
            <hr style="height: 5px;color: red;">
			<%= @student.name%><br>
			<%= @student.email%><br>
			<%= @student.password%><br>
			<%= @student.address%><br>	
		</div>
		<div class="col-sm-4"></div>
	</div>
</div>